openapi: 3.0.3
info:
  contact: {}
  title: Ledger API
  version: "1.0"
servers:
- url: /
security:
- basicAuth: []
paths:
  /_info:
    get:
      operationId: getInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigInfoResponse'
          description: OK
      summary: Show server information.
      tags:
      - server
  /{ledger}/accounts:
    get:
      description: "List accounts from a ledger, sorted by address in descending order."
      operationId: listAccounts
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: "Pagination cursor, will return accounts after given address,\
          \ in descending order."
        explode: true
        in: query
        name: after
        required: false
        schema:
          example: users:003
          type: string
        style: form
      - description: Filter accounts by address pattern (regular expression placed
          between ^ and $).
        explode: true
        in: query
        name: address
        required: false
        schema:
          example: users:.+
          type: string
        style: form
      - description: Filter accounts by metadata key value pairs. Nested objects can
          be used as seen in the example below.
        example: "metadata[key]=value1&metadata[a.nested.key]=value2"
        explode: true
        in: query
        name: metadata
        required: false
        schema:
          properties: {}
          type: object
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAccounts_200_response'
          description: OK
      summary: List accounts from a ledger.
      tags:
      - accounts
    head:
      operationId: countAccounts
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Filter accounts by address pattern (regular expression placed
          between ^ and $).
        explode: true
        in: query
        name: address
        required: false
        schema:
          example: users:.+
          type: string
        style: form
      - description: Filter accounts by metadata key value pairs. Nested objects can
          be used as seen in the example below.
        example: "metadata[key]=value1&metadata[a.nested.key]=value2"
        explode: true
        in: query
        name: metadata
        required: false
        schema:
          properties: {}
          type: object
        style: deepObject
      responses:
        "200":
          description: OK
          headers:
            Count:
              explode: false
              schema:
                type: integer
              style: simple
      summary: Count the accounts from a ledger.
      tags:
      - accounts
  /{ledger}/accounts/{address}:
    get:
      operationId: getAccount
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Exact address of the account.
        explode: false
        in: path
        name: address
        required: true
        schema:
          example: users:001
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccount_200_response'
          description: OK
      summary: Get account by its address.
      tags:
      - accounts
  /{ledger}/accounts/{address}/metadata:
    post:
      operationId: addMetadataToAccount
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Exact address of the account.
        explode: false
        in: path
        name: address
        required: true
        schema:
          example: users:001
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
        description: metadata
        required: true
      responses:
        "204":
          description: Empty response
        "400":
          content: {}
          description: ""
      summary: Add metadata to an account.
      tags:
      - accounts
  /{ledger}/mapping:
    get:
      operationId: getMapping
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingResponse'
          description: OK
      summary: Get the mapping of a ledger.
      tags:
      - mapping
    put:
      operationId: updateMapping
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mapping'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingResponse'
          description: OK
      summary: Update the mapping of a ledger.
      tags:
      - mapping
  /{ledger}/script:
    post:
      operationId: runScript
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Set the preview mode. Preview mode doesn't add the logs to the
          database or publish a message to the message broker.
        explode: true
        in: query
        name: preview
        required: false
        schema:
          example: true
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Script'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScriptResult'
          description: OK
      summary: Execute a Numscript.
      tags:
      - script
  /{ledger}/stats:
    get:
      description: |-
        Get ledger stats (aggregate metrics on accounts and transactions)
        The stats for account
      operationId: readStats
      parameters:
      - description: name of the ledger
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
          description: OK
      summary: Get Stats
      tags:
      - stats
  /{ledger}/transactions:
    get:
      description: "List transactions from a ledger, sorted by txid in descending\
        \ order."
      operationId: listTransactions
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: "Pagination cursor, will return transactions after given txid\
          \ (in descending order)."
        explode: true
        in: query
        name: after
        required: false
        schema:
          example: "1234"
          type: string
        style: form
      - description: Find transactions by reference field.
        explode: true
        in: query
        name: reference
        required: false
        schema:
          example: ref:001
          type: string
        style: form
      - description: "Find transactions with postings involving given account, either\
          \ as source or destination."
        explode: true
        in: query
        name: account
        required: false
        schema:
          example: users:001
          type: string
        style: form
      - description: Find transactions with postings involving given account at source.
        explode: true
        in: query
        name: source
        required: false
        schema:
          example: users:001
          type: string
        style: form
      - description: Find transactions with postings involving given account at destination.
        explode: true
        in: query
        name: destination
        required: false
        schema:
          example: users:001
          type: string
        style: form
      - description: "Filter transactions that occurred after this timestamp.\nThe\
          \ format is RFC3339 and is inclusive (for example, 12:00:01 includes the\
          \ first second of the minute)."
        explode: true
        in: query
        name: start_time
        required: false
        schema:
          type: string
        style: form
      - description: "Filter transactions that occurred before this timestamp.\nThe\
          \ format is RFC3339 and is exclusive (for example, 12:00:01 excludes the\
          \ first second of the minute)."
        explode: true
        in: query
        name: end_time
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listTransactions_200_response'
          description: OK
      summary: List transactions from a ledger.
      tags:
      - transactions
    head:
      operationId: countTransactions
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Filter transactions by reference field.
        explode: true
        in: query
        name: reference
        required: false
        schema:
          example: ref:001
          type: string
        style: form
      - description: "Filter transactions with postings involving given account, either\
          \ as source or destination."
        explode: true
        in: query
        name: account
        required: false
        schema:
          example: users:001
          type: string
        style: form
      - description: Filter transactions with postings involving given account at
          source.
        explode: true
        in: query
        name: source
        required: false
        schema:
          example: users:001
          type: string
        style: form
      - description: Filter transactions with postings involving given account at
          destination.
        explode: true
        in: query
        name: destination
        required: false
        schema:
          example: users:001
          type: string
        style: form
      responses:
        "200":
          description: OK
          headers:
            Count:
              explode: false
              schema:
                type: integer
              style: simple
      summary: Count the transactions from a ledger.
      tags:
      - transactions
    post:
      operationId: createTransaction
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Set the preview mode. Preview mode doesn't add the logs to the
          database or publish a message to the message broker.
        explode: true
        in: query
        name: preview
        required: false
        schema:
          example: true
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionData'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionResponse'
          description: OK
        "304":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionResponse'
          description: Not modified (when preview is enabled)
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Commit error
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Confict
      summary: Create a new transaction to a ledger.
      tags:
      - transactions
  /{ledger}/transactions/{txid}:
    get:
      operationId: getTransaction
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Transaction ID.
        explode: false
        in: path
        name: txid
        required: true
        schema:
          example: 1234
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
      summary: Get transaction from a ledger by its ID.
      tags:
      - transactions
  /{ledger}/transactions/{txid}/metadata:
    post:
      operationId: addMetadataOnTransaction
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Transaction ID.
        explode: false
        in: path
        name: txid
        required: true
        schema:
          example: 1234
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
        description: metadata
      responses:
        "204":
          content: {}
          description: Empty response
      summary: Set the metadata of a transaction by its ID.
      tags:
      - transactions
  /{ledger}/transactions/{txid}/revert:
    post:
      operationId: revertTransaction
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      - description: Transaction ID.
        explode: false
        in: path
        name: txid
        required: true
        schema:
          example: 1234
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
          description: OK
      summary: Revert a ledger transaction by its ID.
      tags:
      - transactions
  /{ledger}/transactions/batch:
    post:
      operationId: CreateTransactions
      parameters:
      - description: Name of the ledger.
        explode: false
        in: path
        name: ledger
        required: true
        schema:
          example: ledger001
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transactions'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactions_200_response'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Commit error
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Conflict
      summary: Create a new batch of transactions to a ledger.
      tags:
      - transactions
components:
  schemas:
    Config:
      example:
        storage:
          driver: driver
          ledgers:
          - ledgers
          - ledgers
      properties:
        storage:
          $ref: '#/components/schemas/LedgerStorage'
      required:
      - storage
      type: object
    Metadata:
      additionalProperties: {}
      example:
        admin: true
        a:
          nested:
            key: value
      nullable: true
      type: object
    ConfigInfo:
      example:
        server: server
        config:
          storage:
            driver: driver
            ledgers:
            - ledgers
            - ledgers
        version: version
      properties:
        config:
          $ref: '#/components/schemas/Config'
        server:
          type: string
        version:
          type: string
      required:
      - config
      - server
      - version
      type: object
    LedgerStorage:
      example:
        driver: driver
        ledgers:
        - ledgers
        - ledgers
      properties:
        driver:
          type: string
        ledgers:
          items:
            type: string
          type: array
      required:
      - driver
      - ledgers
      type: object
    ScriptResult:
      example:
        error_message: error_message
        details: details
        error_code: INTERNAL
        transaction:
          reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          txid: 0
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        details:
          type: string
        error_code:
          enum:
          - INTERNAL
          - INSUFFICIENT_FUND
          - COMPILATION_FAILED
          - NO_SCRIPT
          type: string
        error_message:
          type: string
        transaction:
          $ref: '#/components/schemas/Transaction'
      type: object
    Account:
      properties:
        address:
          example: users:001
          type: string
        type:
          example: virtual
          type: string
        metadata:
          example:
            admin: true
            a:
              nested:
                key: value
          properties: {}
          type: object
      required:
      - address
      type: object
    AccountWithVolumesAndBalances:
      example:
        metadata:
          admin: true
          a:
            nested:
              key: value
        balances:
          COIN: 100
        address: users:001
        volumes:
          COIN:
            input: 100
            output: 0
        type: virtual
      properties:
        address:
          example: users:001
          type: string
        type:
          example: virtual
          type: string
        metadata:
          example:
            admin: true
            a:
              nested:
                key: value
          properties: {}
          type: object
        volumes:
          additionalProperties:
            additionalProperties:
              type: integer
            type: object
          example:
            COIN:
              input: 100
              output: 0
          type: object
        balances:
          additionalProperties:
            type: integer
          example:
            COIN: 100
          type: object
      required:
      - address
      type: object
    Contract:
      example:
        expr: "{}"
        account: users:001
      properties:
        account:
          example: users:001
          type: string
        expr:
          type: object
      required:
      - accounts
      - expr
      type: object
    Mapping:
      example:
        contracts:
        - expr: "{}"
          account: users:001
        - expr: "{}"
          account: users:001
      nullable: true
      properties:
        contracts:
          items:
            $ref: '#/components/schemas/Contract'
          type: array
      required:
      - contracts
      type: object
    Posting:
      example:
        amount: 100
        destination: users:002
        source: users:001
        asset: COIN
      properties:
        amount:
          example: 100
          type: integer
        asset:
          example: COIN
          type: string
        destination:
          example: users:002
          type: string
        source:
          example: users:001
          type: string
      required:
      - amount
      - asset
      - destination
      - source
      type: object
    Script:
      example:
        plain: "vars {\naccount $user\n}\nsend [COIN 10] (\n\tsource = @world\n\t\
          destination = $user\n)\n"
        vars:
          vars:
            user: users:042
      properties:
        plain:
          example: "vars {\naccount $user\n}\nsend [COIN 10] (\n\tsource = @world\n\
            \tdestination = $user\n)\n"
          type: string
        vars:
          example:
            vars:
              user: users:042
          properties: {}
          type: object
      required:
      - plain
      type: object
    Transaction:
      example:
        reference: ref:001
        metadata:
          admin: true
          a:
            nested:
              key: value
        postings:
        - amount: 100
          destination: users:002
          source: users:001
          asset: COIN
        - amount: 100
          destination: users:002
          source: users:001
          asset: COIN
        txid: 0
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        postings:
          items:
            $ref: '#/components/schemas/Posting'
          type: array
        reference:
          example: ref:001
          type: string
        metadata:
          additionalProperties: {}
          example:
            admin: true
            a:
              nested:
                key: value
          nullable: true
          type: object
        timestamp:
          format: date-time
          type: string
        txid:
          type: integer
      required:
      - postings
      - timestamp
      - txid
      type: object
    TransactionData:
      example:
        reference: ref:001
        metadata:
          admin: true
          a:
            nested:
              key: value
        postings:
        - amount: 100
          destination: users:002
          source: users:001
          asset: COIN
        - amount: 100
          destination: users:002
          source: users:001
          asset: COIN
      properties:
        postings:
          items:
            $ref: '#/components/schemas/Posting'
          type: array
        reference:
          example: ref:001
          type: string
        metadata:
          additionalProperties: {}
          example:
            admin: true
            a:
              nested:
                key: value
          nullable: true
          type: object
      required:
      - postings
      type: object
    Transactions:
      example:
        transactions:
        - reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
        - reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
      properties:
        transactions:
          items:
            $ref: '#/components/schemas/TransactionData'
          type: array
      required:
      - transactions
      type: object
    Stats:
      example:
        accounts: 0
        transactions: 6
      properties:
        accounts:
          type: integer
        transactions:
          type: integer
      required:
      - accounts
      - transactions
      type: object
    Cursor:
      properties:
        page_size:
          example: 1
          type: integer
        has_more:
          example: false
          type: boolean
      required:
      - has_more
      - page_size
      type: object
    CreateTransactionResponse:
      example:
        data:
        - reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          txid: 0
          timestamp: 2000-01-23T04:56:07.000+00:00
        - reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          txid: 0
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          items:
            $ref: '#/components/schemas/Transaction'
          type: array
      required:
      - data
      type: object
    TransactionResponse:
      example:
        data:
          reference: ref:001
          metadata:
            admin: true
            a:
              nested:
                key: value
          postings:
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          - amount: 100
            destination: users:002
            source: users:001
            asset: COIN
          txid: 0
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          $ref: '#/components/schemas/Transaction'
      required:
      - data
      type: object
    StatsResponse:
      example:
        data:
          accounts: 0
          transactions: 6
      properties:
        data:
          $ref: '#/components/schemas/Stats'
      required:
      - data
      type: object
    MappingResponse:
      example:
        data:
          contracts:
          - expr: "{}"
            account: users:001
          - expr: "{}"
            account: users:001
      properties:
        data:
          $ref: '#/components/schemas/Mapping'
      type: object
    ConfigInfoResponse:
      example:
        data:
          server: server
          config:
            storage:
              driver: driver
              ledgers:
              - ledgers
              - ledgers
          version: version
      properties:
        data:
          $ref: '#/components/schemas/ConfigInfo'
      required:
      - data
      type: object
    ErrorCode:
      enum:
      - INTERNAL
      - INSUFFICIENT_FUND
      - VALIDATION
      - CONFLICT
      - NOT_FOUND
      type: string
    ErrorResponse:
      properties:
        error_code:
          $ref: '#/components/schemas/ErrorCode'
        error_message:
          example: internal error
          type: string
      required:
      - error_code
      type: object
    listAccounts_200_response_cursor_allOf:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Account'
          type: array
      required:
      - data
      type: object
    listAccounts_200_response_cursor:
      allOf:
      - $ref: '#/components/schemas/Cursor'
      - $ref: '#/components/schemas/listAccounts_200_response_cursor_allOf'
    listAccounts_200_response:
      example:
        cursor: null
      properties:
        cursor:
          $ref: '#/components/schemas/listAccounts_200_response_cursor'
      required:
      - cursor
    getAccount_200_response:
      example:
        data:
          metadata:
            admin: true
            a:
              nested:
                key: value
          balances:
            COIN: 100
          address: users:001
          volumes:
            COIN:
              input: 100
              output: 0
          type: virtual
      properties:
        data:
          $ref: '#/components/schemas/AccountWithVolumesAndBalances'
      required:
      - data
      type: object
    listTransactions_200_response_cursor_allOf:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Transaction'
          type: array
      required:
      - data
      type: object
    listTransactions_200_response_cursor:
      allOf:
      - $ref: '#/components/schemas/Cursor'
      - $ref: '#/components/schemas/listTransactions_200_response_cursor_allOf'
    listTransactions_200_response:
      example:
        cursor: null
      properties:
        cursor:
          $ref: '#/components/schemas/listTransactions_200_response_cursor'
      required:
      - cursor
      type: object
    CreateTransactions_200_response_allOf:
      properties:
        cursor:
          $ref: '#/components/schemas/Cursor'
      type: object
    CreateTransactions_200_response:
      allOf:
      - $ref: '#/components/schemas/CreateTransactions_200_response_allOf'
      - $ref: '#/components/schemas/listTransactions_200_response_cursor_allOf'
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
